version: '3.7'
services:
  vue:
    container_name: vue-agora
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/agora-code
      - /agora-code/node_modules